installCRDs: false
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true 
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: prometheus.donfolayan.com
        paths: