apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod
  namespace: sock-shop
spec:
  dnsNames:
    - capstone.donfolayan.me
    - grafana.donfolayan.me
    - prometheus.donfolayan.me
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: letsencrypt-prod
  secretName: letsencrypt-prod-tls
  usages:
    - digital signature
    - key encipherment
