apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx-controller
subjects:
  - kind: ServiceAccount
    name: ingress-nginx-controller
    namespace: ingress-nginx
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io