name: Azure AKS Monitoring

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  AKS-Cluster-Monitoring:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Resource Group (if not exists)
        run: |
          az group create --name sockshop_capstone-rg --location "East US 2"
        
      - name: Assign User Access Administrator Role
        run: |
          az role assignment create --role "User Access Administrator" --assignee ${{ secrets.AZURE_CLIENT_ID }} --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Key Vault
        run: |
          az keyvault create --name "sockshop" --resource-group sockshop_capstone-rg --location "East US 2" || echo "Key Vault already exists"

      - name: Assign Permissions to Service Principal
        run: |
          az role assignment create --role "Key Vault Secrets Officer" --assignee ${{ secrets.AZURE_CLIENT_ID }} --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/sockshop_capstone-rg/providers/Microsoft.KeyVault/vaults/sockshop

      - name: Store Secrets in Key Vault
        run: |
          az keyvault secret set --vault-name "sockshop" --name "client-id" --value "${{ secrets.AZURE_CLIENT_ID }}"
          az keyvault secret set --vault-name "sockshop" --name "password" --value "${{ secrets.PASSWORD }}"
          az keyvault secret set --vault-name "sockshop" --name "subscription-id" --value "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Get Key Vault ID
        id: get_kv_id
        run: |
          echo "keyvault_id=$(az keyvault show --name sockshop --query id -o tsv)" >> $GITHUB_ENV
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: latest

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Import Resource
        id: import_rg
        run: |
          set +e  # Disable exit on error
          terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/sockshop_capstone-rg
          echo "Import step completed."
          set -e  # Re-enable exit on error    
    
      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve
          
      - name: Terraform Output
        run: terraform output
          
      - name: AKS Monitoring Enabler
        run: |
          cluster_name=$(terraform output kubernetes_cluster_name | tr -d '"')
          az aks get-credentials -n "$cluster_name" -g "sockshop_capstone-rg"
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update
          
          # Install Prometheus
          helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace
      
      - name: Terraform Destroy
        if: failure()
        run: terraform destroy --auto-approve
