name: Azure AKS Monitoring

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  AKS-Cluster-Monitoring:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Resource Group (if not exists)
        run: |
          az group create --name sockshop_capstone-rg --location "East US 2"

      - name: Create Key Vault
        run: |
          az keyvault create --name "sockshop" --resource-group sockshop_capstone-rg --location <your-location> || echo "Key Vault already exists"

      - name: Assign Permissions to Service Principal
        run: |
          az keyvault set-policy --name "sockshop" --spn ${{ secrets.AZURE_CLIENT_ID }} --secret-permissions get set list delete

      - name: Store Secrets in Key Vault
        run: |
          az keyvault secret set --vault-name "sockshop" --name "client-id" --value "${{ secrets.AZURE_CLIENT_ID }}"
          az keyvault secret set --vault-name "sockshop" --name "password" --value "${{ secrets.PASSWORD }}"
          az keyvault secret set --vault-name "sockshop" --name "tenant-id" --value "${{ secrets.AZURE_TENANT_ID }}"

      - name: Get Key Vault ID
        id: get_kv_id
        run: |
          echo "keyvault_id=$(az keyvault show --name sockshop --query id -o tsv)" >> $GITHUB_ENV
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: latest

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="keyvault_id=${{ env.keyvault_id }}"
          
      - name: Terraform Output
        id: output
        run: |
          terraform output -json > outputs.json
          echo "aks_cluster_name=$(jq -r .kubernetes_cluster_name.value outputs.json)" >> $GITHUB_ENV

      - name: AKS Monitoring Enabler
        run: |
          az aks get-credentials -n ""${{ env.aks_cluster_name }}"" -g "sockshop_capstone-rg"
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update
          
          # Install Prometheus
          helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace